version: "3.9"

services:
  vite-app:
    build: .
    command: npm run dev
    ports:
      - "4173:4173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
